package com.chenhy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImportHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportHistoryAllPropertiesEquals(ImportHistory expected, ImportHistory actual) {
        assertImportHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertImportHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportHistoryAllUpdatablePropertiesEquals(ImportHistory expected, ImportHistory actual) {
        assertImportHistoryUpdatableFieldsEquals(expected, actual);
        assertImportHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportHistoryAutoGeneratedPropertiesEquals(ImportHistory expected, ImportHistory actual) {
        assertThat(actual)
            .as("Verify ImportHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportHistoryUpdatableFieldsEquals(ImportHistory expected, ImportHistory actual) {
        assertThat(actual)
            .as("Verify ImportHistory relevant properties")
            .satisfies(a -> assertThat(a.getUuid()).as("check uuid").isEqualTo(expected.getUuid()))
            .satisfies(a -> assertThat(a.getTcihCode()).as("check tcihCode").isEqualTo(expected.getTcihCode()))
            .satisfies(a -> assertThat(a.getTcihFilename()).as("check tcihFilename").isEqualTo(expected.getTcihFilename()))
            .satisfies(a -> assertThat(a.getTcihImporttime()).as("check tcihImporttime").isEqualTo(expected.getTcihImporttime()))
            .satisfies(a -> assertThat(a.getTcihStatus()).as("check tcihStatus").isEqualTo(expected.getTcihStatus()))
            .satisfies(a -> assertThat(a.getCreateBy()).as("check createBy").isEqualTo(expected.getCreateBy()))
            .satisfies(a -> assertThat(a.getCreateTime()).as("check createTime").isEqualTo(expected.getCreateTime()))
            .satisfies(a -> assertThat(a.getUpdateBy()).as("check updateBy").isEqualTo(expected.getUpdateBy()))
            .satisfies(a -> assertThat(a.getUpdateTime()).as("check updateTime").isEqualTo(expected.getUpdateTime()))
            .satisfies(a -> assertThat(a.getDelFlag()).as("check delFlag").isEqualTo(expected.getDelFlag()))
            .satisfies(a -> assertThat(a.getRemark()).as("check remark").isEqualTo(expected.getRemark()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportHistoryUpdatableRelationshipsEquals(ImportHistory expected, ImportHistory actual) {
        // empty method
    }
}
