package com.chenhy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImportSettingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportSettingAllPropertiesEquals(ImportSetting expected, ImportSetting actual) {
        assertImportSettingAutoGeneratedPropertiesEquals(expected, actual);
        assertImportSettingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportSettingAllUpdatablePropertiesEquals(ImportSetting expected, ImportSetting actual) {
        assertImportSettingUpdatableFieldsEquals(expected, actual);
        assertImportSettingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportSettingAutoGeneratedPropertiesEquals(ImportSetting expected, ImportSetting actual) {
        assertThat(actual)
            .as("Verify ImportSetting auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportSettingUpdatableFieldsEquals(ImportSetting expected, ImportSetting actual) {
        assertThat(actual)
            .as("Verify ImportSetting relevant properties")
            .satisfies(a -> assertThat(a.getTcisCode()).as("check tcisCode").isEqualTo(expected.getTcisCode()))
            .satisfies(a -> assertThat(a.getTcisType()).as("check tcisType").isEqualTo(expected.getTcisType()))
            .satisfies(a -> assertThat(a.getTcisIncol()).as("check tcisIncol").isEqualTo(expected.getTcisIncol()))
            .satisfies(a -> assertThat(a.getTcisEditrule()).as("check tcisEditrule").isEqualTo(expected.getTcisEditrule()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportSettingUpdatableRelationshipsEquals(ImportSetting expected, ImportSetting actual) {
        // empty method
    }
}
